#!/usr/bin/env python3
"""Generate Android resources from the canonical iOS string catalog."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "HermesMobile" / "Resources" / "Localizable.xcstrings"
ALIASES_SOURCE = ROOT / "ci" / "android_localization_aliases.json"
SUPPLEMENTAL_SOURCE = ROOT / "ci" / "android_supplemental_localizations.json"
ANDROID_RES = ROOT / "android" / "app" / "src" / "main" / "res"
KOTLIN_OUTPUT = (
    ROOT
    / "android"
    / "app"
    / "src"
    / "main"
    / "java"
    / "com"
    / "uzairansar"
    / "hermex"
    / "ui"
    / "localization"
    / "AndroidLocalizationCatalog.kt"
)

LOCALE_DIRECTORIES = {
    "en": "values",
    "ar": "values-ar",
    "de": "values-de",
    "es": "values-es",
    "fr": "values-fr",
    "he": "values-iw",
    "it": "values-it",
    "ja": "values-ja",
    "ko": "values-ko",
    "nl": "values-nl",
    "pl": "values-pl",
    "pt-BR": "values-pt-rBR",
    "ru": "values-ru",
    "tr": "values-tr",
    "ur": "values-ur",
    "zh-HK": "values-zh-rHK",
    "zh-Hans": "values-zh-rCN",
    "zh-Hant": "values-zh-rTW",
}


def resource_name(key: str) -> str:
    return f"l10n_{hashlib.sha1(key.encode('utf-8')).hexdigest()[:16]}"


def localized_value(payload: dict[str, Any] | None) -> str | None:
    if not payload:
        return None
    unit = payload.get("stringUnit")
    if isinstance(unit, dict) and isinstance(unit.get("value"), str):
        return unit["value"]
    variations = payload.get("variations")
    if not isinstance(variations, dict):
        return None
    plural = variations.get("plural")
    if isinstance(plural, dict):
        for category in ("other", "one", "zero", "two", "few", "many"):
            value = localized_value(plural.get(category))
            if value is not None:
                return value
    for value in variations.values():
        if isinstance(value, dict):
            resolved = localized_value(value)
            if resolved is not None:
                return resolved
    return None


def plural_values(payload: dict[str, Any] | None) -> dict[str, str]:
    if not payload:
        return {}
    variations = payload.get("variations")
    if not isinstance(variations, dict):
        return {}
    plural = variations.get("plural")
    if not isinstance(plural, dict):
        return {}
    return {
        category: value
        for category in ("zero", "one", "two", "few", "many", "other")
        if (value := localized_value(plural.get(category))) is not None
    }


def android_xml_value(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace("\r\n", "\n")
        .replace("\r", "\n")
        .replace("\n", "\\n")
        .replace('"', '\\"')
    )
    return html.escape(f'"{escaped}"', quote=False)


def android_plural_xml_value(value: str) -> str:
    android_format = (
        value.replace("%lld", "%d")
        .replace("%ld", "%d")
        .replace("%@", "%s")
    )
    escaped = (
        android_format.replace("\\", "\\\\")
        .replace("\r\n", "\n")
        .replace("\r", "\n")
        .replace("\n", "\\n")
        .replace('"', '\\"')
    )
    return html.escape(f'"{escaped}"', quote=False)


def kotlin_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


def xml_content(
    locale: str,
    entries: dict[str, dict[str, Any]],
    aliases: dict[str, str],
    platform_aliases: dict[str, dict[str, Any]],
    supplemental: dict[str, dict[str, str]],
) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by ci/generate_android_localization_catalog.py. -->",
        "<resources>",
    ]
    for key in sorted(entries):
        entry = entries[key]
        localization = entry.get("localizations", {}).get(locale)
        if locale == "en":
            localization = entry.get("localizations", {}).get("en")
            value = localized_value(localization) or key
        else:
            value = localized_value(localization) or key
        lines.append(
            f'    <string name="{resource_name(key)}" formatted="false">{android_xml_value(value)}</string>'
        )
        plurals = plural_values(localization)
        if plurals:
            lines.append(f'    <plurals name="{resource_name(key)}">')
            fallback_plural = plurals.get("other") or plurals.get("one")
            for category in ("zero", "one", "two", "few", "many", "other"):
                plural_value = plurals.get(category) or fallback_plural
                if plural_value is None:
                    continue
                lines.append(
                    f'        <item quantity="{category}">{android_plural_xml_value(plural_value)}</item>'
                )
            lines.append("    </plurals>")
    for key in sorted(aliases):
        if key in entries:
            continue
        if locale == "en":
            value = key
        else:
            source_entry = entries[aliases[key]]
            value = localized_value(source_entry.get("localizations", {}).get(locale)) or key
        lines.append(
            f'    <string name="{resource_name(key)}" formatted="false">{android_xml_value(value)}</string>'
        )
    for key in sorted(platform_aliases):
        if key in entries or key in aliases:
            continue
        alias = platform_aliases[key]
        source_key = alias["source"]
        source_entry = entries[source_key]
        if locale == "en":
            value = localized_value(source_entry.get("localizations", {}).get("en")) or source_key
        else:
            value = localized_value(source_entry.get("localizations", {}).get(locale)) or source_key
        for old, new in alias.get("replace", {}).items():
            value = value.replace(old, new)
        lines.append(
            f'    <string name="{resource_name(key)}" formatted="false">{android_xml_value(value)}</string>'
        )
    for key in sorted(supplemental):
        if key in entries or key in aliases or key in platform_aliases:
            continue
        value = supplemental[key][locale]
        lines.append(
            f'    <string name="{resource_name(key)}" formatted="false">{android_xml_value(value)}</string>'
        )
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def kotlin_content(
    entries: dict[str, dict[str, Any]],
    aliases: dict[str, str],
    platform_aliases: dict[str, dict[str, Any]],
    supplemental: dict[str, dict[str, str]],
) -> str:
    lines = [
        "// Generated by ci/generate_android_localization_catalog.py.",
        "package com.uzairansar.hermex.ui.localization",
        "",
        "import androidx.annotation.StringRes",
        "import androidx.annotation.PluralsRes",
        "import com.uzairansar.hermex.R",
        "",
        "internal object AndroidLocalizationCatalog {",
        "    private val resourcesByEnglishText: Map<String, Int> = mapOf(",
    ]
    for key in sorted(entries):
        lines.append(f'        "{kotlin_string(key)}" to R.string.{resource_name(key)},')
    for key in sorted(aliases):
        if key in entries:
            continue
        lines.append(f'        "{kotlin_string(key)}" to R.string.{resource_name(key)},')
    for key in sorted(platform_aliases):
        if key in entries or key in aliases:
            continue
        lines.append(f'        "{kotlin_string(key)}" to R.string.{resource_name(key)},')
    for key in sorted(supplemental):
        if key in entries or key in aliases or key in platform_aliases:
            continue
        lines.append(f'        "{kotlin_string(key)}" to R.string.{resource_name(key)},')
    lines.extend(
        [
            "    )",
            "",
            "    private val pluralsByEnglishText: Map<String, Int> = mapOf(",
        ]
    )
    for key in sorted(entries):
        if any(
            plural_values(payload)
            for payload in entries[key].get("localizations", {}).values()
            if isinstance(payload, dict)
        ):
            lines.append(f'        "{kotlin_string(key)}" to R.plurals.{resource_name(key)},')
    lines.extend(
        [
            "    )",
            "",
            f"    const val sourceEntryCount: Int = {len(entries)}",
            "    val entryCount: Int = resourcesByEnglishText.size",
            "",
            "    @StringRes",
            "    fun resourceId(englishText: String): Int? = resourcesByEnglishText[englishText]",
            "",
            "    @PluralsRes",
            "    fun pluralResourceId(englishText: String): Int? = pluralsByEnglishText[englishText]",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != content:
            raise SystemExit(f"Generated localization file is stale: {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale.")
    args = parser.parse_args()
    catalog = json.loads(SOURCE.read_text(encoding="utf-8"))
    entries = catalog.get("strings", {})
    if not isinstance(entries, dict) or not entries:
        raise SystemExit(f"No strings found in {SOURCE}")
    alias_catalog = json.loads(ALIASES_SOURCE.read_text(encoding="utf-8"))
    supplemental = json.loads(SUPPLEMENTAL_SOURCE.read_text(encoding="utf-8"))
    aliases = alias_catalog.get("aliases", {})
    platform_aliases = alias_catalog.get("platform_aliases", {})
    missing_sources = sorted(
        ({*aliases.values()} | {value["source"] for value in platform_aliases.values()}) - set(entries)
    )
    if missing_sources:
        raise SystemExit(f"Localization aliases reference missing iOS keys: {missing_sources}")
    required_locales = set(LOCALE_DIRECTORIES)
    incomplete_supplemental = {
        key: sorted(required_locales - set(values))
        for key, values in supplemental.items()
        if required_locales - set(values)
    }
    if incomplete_supplemental:
        raise SystemExit(f"Supplemental Android localizations are incomplete: {incomplete_supplemental}")
    for locale in LOCALE_DIRECTORIES:
        output = ANDROID_RES / LOCALE_DIRECTORIES[locale] / "localization_catalog.xml"
        write_or_check(output, xml_content(locale, entries, aliases, platform_aliases, supplemental), args.check)
    write_or_check(KOTLIN_OUTPUT, kotlin_content(entries, aliases, platform_aliases, supplemental), args.check)
    verb = "Verified" if args.check else "Generated"
    total = len(set(entries) | set(aliases) | set(platform_aliases) | set(supplemental))
    print(f"{verb} {total} Android localization keys from {len(entries)} iOS entries for {len(LOCALE_DIRECTORIES)} locales.")


if __name__ == "__main__":
    main()
